[package]
name = "devbox"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking"] }
local-ip-address = "0.5"
clap_complete = "4.5.55"
