name: Release

# Tarvitsee write‑oikeudet GitHub Releasejen hallintaan
permissions:
  contents: write

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build-release:
    # Ajetaan sekä Linux- että Windows‑runnerilla
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build release
      run: cargo build --release

    - name: Package binary (Linux)
      if: runner.os == 'Linux'
      run: |
        mkdir -p dist
        cp target/release/devbox dist/devbox-linux-${{ github.ref_name }}

    - name: Package binary (Windows)
      if: runner.os == 'Windows'
      run: |
        mkdir dist
        copy target\\release\\devbox.exe dist\\devbox-windows-${{ github.ref_name }}.exe

    - name: Create GitHub Release & upload assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
